spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

logging:
  level:
    root: WARN
    com.company.alm: INFO
  file:
    name: logs/application.log
    max-size: 50MB
    max-history: 90
